deploy:
  skip_cleanup: true
  git:
  quiet: true
matrix:
  include:
    - language:java
    jdk:
    - oraclejdk8
    - oraclejdk10
    - oraclejdk-ea
    - openjdk10
    - openjdk11
    before_install:
    - cd java
    #the path to the file to execute the test
    
    -language: node_js
    node_js:
     - "iojs"
     - "7"
    #the path to the file to execute the test
    -language: php
      php:
      - 5.4
      - 5.5
      before_install:
      - cd php
      script:
      - phpunit --bootstrap src/autoload.php --debug --coverage-text test
notifications:
  email:
    - 1272371@students.wits.ac.za
    

