language: php
php:
  - '7.1'
before_install:
  - travis_retry composer self-update
  #try to install php_xdebug for codecover and clover files
  - sudo apt-get install php-xdebug
script:
  - composer install -n --prefer-dist
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false