language: php
php:
  - '7.1'
before_install:
  - travis_retry composer self-update
before_script:
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - composer update
script:
  - phpunit --configuration=phpunit.xml --coverage-text
  - phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)