language: php
php:
  - '7.1'
before_install:
  - travis_retry composer self-update
script:
  - composer install -n --prefer-dist
  - phpunit --coverage-clover coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)