language: php

php:
  - '5.6'
  - '7.2'

before_install:
  - travis_retry composer self-update

before_script:
  - composer install

script:
  - phpunit --configuration phpunit.xml --coverage-text
  - phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)