language: php
php:
  - '7.1'
before_install:
  - travis_retry composer self-update
before_script:
  - curl -sS https://getcomposer.org/installer | php
script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text
  - vendor/bin/phpunit --coverage-clover coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)