deploy:
  skip_cleanup: true
  git:
  quiet: true
matrix:
  include:
  #java
    - language:java
    jdk:
    - oraclejdk8
    - oraclejdk10
    - oraclejdk-ea
    - openjdk10
    - openjdk11
    script:
    - make test
    before_install:
    - cd java
    
    #javascript
    -language: node_js
    node_js:
     - "iojs"
     - "7"
     
     #php
    -language: php
      php:
      - 5.4
      - 5.5
      before_install:
      - cd php
      script:
      - phpunit --bootstrap src/autoload.php --debug --coverage-text test
      
  services:
  - mysql
  addons:
     apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
  # blocklist
  branches:
   except:
   - gh-pages
  test:
  adapter: mysql2
  database: risk
  username: 1234567
  password:password
  encoding: utf8
  before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS risk;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='1234567'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
notifications:
  email:
    - 1272371@students.wits.ac.za
    

