language: php
php:
  - '7.2'
before_install:
  - travis_retry composer install --no-interaction --prefer-source --dev
  - composer install -n --prefer-dist
  - travis_retry composer self-update
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
