language: php
php:
  - '7.1'
before_install:
  - travis_retry composer self-update
before_script:
  - composer require --dev phpunit/phpunit ^7.3.4
script:
  - phpunit --configuration=phpunit.xml --coverage-text
  - phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)