language: php
php:
  - '7.2'
before_install:
  - travis_retry composer self-update
 script:
  - composer install -n --prefer-dist
  - phpunit
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false