deploy:
  skip_cleanup: true
  git:
  quiet: true
matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - cd backend/tests
      script:
        - python -m unittest discover

    - language:java
    jdk:
    - oraclejdk8
    - oraclejdk10
    - oraclejdk-ea
    - openjdk10
    - openjdk11
    
    -language: node_js
    node_js:
     - "iojs"
     - "7"

notifications:
  email:
    - 1272371@students.wits.ac.za
    
