deploy:
  skip_cleanup: true
  git:
  quiet: true
matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - cd backend/tests
      script:
        - python -m unittest discover
        #the path to the file to execute the test

    - language:java
    jdk:
    - oraclejdk8
    - oraclejdk10
    - oraclejdk-ea
    - openjdk10
    - openjdk11
    #the path to the file to execute the test
    -language: node_js
    node_js:
     - "iojs"
     - "7"
    #the path to the file to execute the test
notifications:
  email:
    - 1272371@students.wits.ac.za
    

